### ISSUE TITLE
for 复制时模板背景丢失

### ISSUE THREAD

**Issue by xiaofeng68** [jinceon/simple-ppt-engine#1]
通过for slide时，生成的背景色以及文字样式丢失。

**Comment by jinceon** [comment]
使用了幻灯片母版，是吗？

**Comment by xiaofeng68** [comment]
对的，问题已解决，谢谢。



xiao_feng68




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年05月07日 10:38 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [jinceon/simple-ppt-engine] for 复制时模板背景丢失 (Issue #1) |

使用了幻灯片母版，是吗？

**Comment by jinceon** [comment]
方便提交一个示例吗？
我今天突然觉得，母版也许是个合理的需求。
也许应该在引擎层面对它提供支持
